flexicon:
  build: ./
  ports:
    - "3000:3000"
  command: /rails/flexicon/rails-entrypoint.sh
  links:
    - mysql:mysql
mysql:
  image: mysql:5.7
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: letmein00
